name: Compile LaTeX document

on:
  push:
    branches:
      - main # o un altro branch di tua scelta
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v2
        with:
          latexmk: true

      - name: Compile LaTeX document
        run: latexmk -pdf -f -interaction=nonstopmode -synctex=1 meccanica-analitica.tex
        run: latexmk -pdf -f -interaction=nonstopmode -synctex=1 fenomeni-ondulatori.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-document
          path: your_document.pdf
