name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Compile LaTeX sources
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          latexmk_use_lualatex: true
          texlive_version: 2023
          root_file: |
            meccanica-analitica.tex
            fenomeni-ondulatori.tex

      - name: Create output directory
        run: mkdir -p dist
        shell: bash

      - name: Move PDFs
        run: mv *.pdf dist/
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-documents
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: compiled-documents
          path: compiled-documents

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard
          cp -r compiled-documents/* .
          git add .
          git commit -m "Update compiled documents"
          git push origin gh-pages --force

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
