name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Compile LaTeX sources
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          latexmk_use_lualatex: true
          texlive_version: 2023
          root_file: |
            meccanica-analitica.tex
            fenomeni-ondulatori.tex

      - name: Create output directory
        run: mkdir -p dist
        shell: bash

      - name: Move PDFs
        run: mv *.pdf dist/
        shell: bash

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: compiled-documents
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-pages-artifact@v1
        with:
          name: compiled-documents

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages # Specifichiamo il branch per il deploy

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
